/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWithdrawRouteImport } from './routes/_authenticated/withdraw'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedLoanPaymentRouteImport } from './routes/_authenticated/loan-payment'
import { Route as AuthenticatedKycRouteImport } from './routes/_authenticated/kyc'
import { Route as AuthenticatedInvestRouteImport } from './routes/_authenticated/invest'
import { Route as AuthenticatedIntensivePaymentRouteImport } from './routes/_authenticated/intensive-payment'
import { Route as AuthenticatedDepositRouteImport } from './routes/_authenticated/deposit'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWithdrawRoute = AuthenticatedWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLoanPaymentRoute =
  AuthenticatedLoanPaymentRouteImport.update({
    id: '/loan-payment',
    path: '/loan-payment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKycRoute = AuthenticatedKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvestRoute = AuthenticatedInvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntensivePaymentRoute =
  AuthenticatedIntensivePaymentRouteImport.update({
    id: '/intensive-payment',
    path: '/intensive-payment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDepositRoute = AuthenticatedDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deposit': typeof AuthenticatedDepositRoute
  '/intensive-payment': typeof AuthenticatedIntensivePaymentRoute
  '/invest': typeof AuthenticatedInvestRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/loan-payment': typeof AuthenticatedLoanPaymentRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deposit': typeof AuthenticatedDepositRoute
  '/intensive-payment': typeof AuthenticatedIntensivePaymentRoute
  '/invest': typeof AuthenticatedInvestRoute
  '/kyc': typeof AuthenticatedKycRoute
  '/loan-payment': typeof AuthenticatedLoanPaymentRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deposit': typeof AuthenticatedDepositRoute
  '/_authenticated/intensive-payment': typeof AuthenticatedIntensivePaymentRoute
  '/_authenticated/invest': typeof AuthenticatedInvestRoute
  '/_authenticated/kyc': typeof AuthenticatedKycRoute
  '/_authenticated/loan-payment': typeof AuthenticatedLoanPaymentRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/withdraw': typeof AuthenticatedWithdrawRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/change-password'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/deposit'
    | '/intensive-payment'
    | '/invest'
    | '/kyc'
    | '/loan-payment'
    | '/transactions'
    | '/withdraw'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/change-password'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/deposit'
    | '/intensive-payment'
    | '/invest'
    | '/kyc'
    | '/loan-payment'
    | '/transactions'
    | '/withdraw'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/change-password'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/deposit'
    | '/_authenticated/intensive-payment'
    | '/_authenticated/invest'
    | '/_authenticated/kyc'
    | '/_authenticated/loan-payment'
    | '/_authenticated/transactions'
    | '/_authenticated/withdraw'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/withdraw': {
      id: '/_authenticated/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof AuthenticatedWithdrawRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loan-payment': {
      id: '/_authenticated/loan-payment'
      path: '/loan-payment'
      fullPath: '/loan-payment'
      preLoaderRoute: typeof AuthenticatedLoanPaymentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kyc': {
      id: '/_authenticated/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof AuthenticatedKycRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invest': {
      id: '/_authenticated/invest'
      path: '/invest'
      fullPath: '/invest'
      preLoaderRoute: typeof AuthenticatedInvestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intensive-payment': {
      id: '/_authenticated/intensive-payment'
      path: '/intensive-payment'
      fullPath: '/intensive-payment'
      preLoaderRoute: typeof AuthenticatedIntensivePaymentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deposit': {
      id: '/_authenticated/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof AuthenticatedDepositRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepositRoute: typeof AuthenticatedDepositRoute
  AuthenticatedIntensivePaymentRoute: typeof AuthenticatedIntensivePaymentRoute
  AuthenticatedInvestRoute: typeof AuthenticatedInvestRoute
  AuthenticatedKycRoute: typeof AuthenticatedKycRoute
  AuthenticatedLoanPaymentRoute: typeof AuthenticatedLoanPaymentRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedWithdrawRoute: typeof AuthenticatedWithdrawRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepositRoute: AuthenticatedDepositRoute,
  AuthenticatedIntensivePaymentRoute: AuthenticatedIntensivePaymentRoute,
  AuthenticatedInvestRoute: AuthenticatedInvestRoute,
  AuthenticatedKycRoute: AuthenticatedKycRoute,
  AuthenticatedLoanPaymentRoute: AuthenticatedLoanPaymentRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedWithdrawRoute: AuthenticatedWithdrawRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
